version: '3.1'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "3001:8080"
  kgs:
    build: ./kgs
    secrets:
    - kgs_secret
    ports:
      - "3002:8081"