services:
  database:
    image: mongo:latest
    container_name: 'my-mongo-container'
    environment:
      - MONGO_DB_NAME=matcher
      - MONGO_DB_USER=matcher
      - MONGO_DB_PASSWORD=matcher
    volumes:
      - /data/db
    ports:
      - 27019:27019