version: '3.1'

services:
  kgs-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db-kgs
    networks:
      - matcher-network
  kgs:
    build: ./kgs
    networks:
      - matcher-network
    ports:
      - "8081:8081"
    depends_on:
      - kgs-mongo
    environment:
      DB_HOST: kgs-mongo
      DB_NAME: matcher
      DB_PASSWORD: matcher
      DB_USER: matcher
      DB_PORT: 27017

  backend-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db-backend
    networks:
      - matcher-network
  backend:
    build: ./backend
    ports:
      - "3001:8080"
    networks:
      - matcher-network
    depends_on:
    - backend-mongo
    - kgs
    environment:
      KEYGEN_HOST: kgs
      KEYGEN_PORT: 8081
      DB_HOST: backend-mongo
      DB_NAME: matcher
      DB_PASSWORD: matcher
      DB_USER: matcher
      DB_PORT: 27017

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_ENDPOINT: http://localhost:3001/api
    networks:
      - matcher-network
  nginx:
    image: nginx
    ports:
    - "80:8000"
    volumes:
    - ./nginxconf/:/etc/nginx/conf.d/
    depends_on:
      - backend
      - frontend
    networks:
      - matcher-network

networks:
  matcher-network:
    external: true